#!/bin/bash

set -e

ACTION="$1"
if [ "$DEBCONF_RECONFIGURE" == "1" ]; then
    ACTION="reconfigure"
fi

# Only run on fresh install or reconfigure
if [ "$ACTION" != 'triggered' ] && ([ -z "$2" ] || [ "$ACTION" != 'configure' ]); then
    systemctl daemon-reload
    systemctl enable --now "timetraveler-scan-config.timer"
fi

