#!/bin/bash

set -e

ACTION="$1"
if [ "$DEBCONF_RECONFIGURE" == "1" ]; then
    ACTION="reconfigure"
fi

# Only run on fresh install or reconfigure
if [ "$ACTION" != 'triggered' ] && ([ -z "$2" ] || [ "$ACTION" != 'configure' ]); then
    systemctl daemon-reload

    if [ -n "$SUDO_USER" ]; then
        systemctl enable --now "timetraveler-scan-config@$SUDO_USER.timer"
    else
        >&2 echo
        >&2 echo "W: Not enabling timetraveler scan-config because you're running"
        >&2 echo "   your setup as the root user, rather than with sudo."
        >&2 echo
        >&2 echo "   To enable regular config scanning, just run"
        >&2 echo "   systemctl enable --now timetraveler-scan-config@\$USER.timer"
        >&2 echo
    fi
fi

