#!/bin/bash

set -e
D="$(dirname "$(readlink -f "$0")")"
for libdir in "$TT_LIBDIR" /usr/share/timetraveler "$D"; do
    if [ -e "$libdir/timetraveler.lib.sh" ]; then
        . "$libdir/timetraveler.lib.sh"
        lib_loaded=true
        break
    fi
done
if [ "$lib_loaded" != "true" ]; then
    >&2 echo
    >&2 echo "E: Couldn't find timetraveler libraries! Are you sure you've installed"
    >&2 echo "   timetraveler correctly?"
    >&2 echo
    exit 1
fi


export TT_VERSION=0.1.1

# Initial loop to gather global options and main command
while test $# -gt 0; do
    case "$1" in
        backup|scan-config|find|search)
            COMMAND="$1"
            shift
            break

        ;;

        -h|--help)
            echo_usage
            exit
        ;;

        --version)
            echo
            echo "$(basename "$0") version $TT_VERSION"
            echo
            echo "See readme and license information, file bug reports, and view source code at"
            echo "https://github.com/kael-shipman/timetraveler"
            echo
            exit
        ;;

        # No other global options for now, so everything else is an error
        *)
            >&2 echo
            >&2 echo "E: Illegal command or option '$1'"
            >&2 echo
            echo_usage >&2
            exit 1
        ;;
    esac
done



# Validate empties
if [ -z ${COMMAND+x} ]; then
    >&2 echo
    >&2 echo "E: You haven't passed a command!"
    >&2 echo
    echo_usage >&2
    exit 2
fi



# Run subcommand

# See if it's on the path
if ! CMD="$(command -v "timetraveler-$COMMAND")"; then
    # Otherwise, see if it's in the same directory as the current file
    CMD="$D/timetraveler-$COMMAND"
    if [ ! -e "$CMD" ]; then
        >&2 echo
        >&2 echo "E: Couldn't find subcommand timetraveler-$COMMAND! Are you sure timetraveler"
        >&2 echo "   is properly installed?"
        >&2 echo
        exit 3
    fi
fi

"$CMD" $@

